name: Hello GitHub Actions

on: push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Say hello
      run: |
        echo Hello
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Say name
      env:
        MY_VAR: GitHub Actions
      run: |
        echo $MY_VAR.
